// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzvtmmcrfnzztvyihplj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dnRtbWNyZm56enR2eWlocGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDc1NjEsImV4cCI6MjA3MjY4MzU2MX0.w6shQNHO-gaVw9eN0hySd2AnSd2qCnipUmv-kLzY_Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});